# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         URI-imaps
version:      1.02
version_from: lib/URI/imaps.pm
installdirs:  site
requires:
    URI:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
